services:
  # Base de donn√©es PostgreSQL
  - type: pserv
    name: erols-db
    plan: free
    ipAllowList: []

  # Application Django
  - type: web
    name: erols-backend
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://erols.netlify.app
      - key: DATABASE_URL
        fromDatabase:
          name: erols-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_CLIENT_ID
        sync: false
      - key: FACEBOOK_CLIENT_SECRET
        sync: false
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2"